name: 'Update'

inputs:
  version:
    required: true
  download_url:
    required: true
  changelog:
    required: false
  changelog_extract:
    required: false

outputs:
  updated:
    description: Whether the update was needed and completed or not
    value: ${{ steps.completed-job.outputs.updated }}
  version:
    description: The version
    value: ${{ steps.completed-job.outputs.version }}

runs:
  using: 'composite'
  steps:
    - name: Install requirements
      shell: bash
      run: sudo apt-get install -y libarchive-tools

    - name: Fetch tags
      shell: bash
      run: git fetch --prune --unshallow --tags

    - name: Check if latest version exists
      shell: bash
      run: |
        if git show-ref --tags --verify --quiet "refs/tags/${{ inputs.version }}"; then
          echo "RUN_BUILD=false" >> "$GITHUB_ENV"
        else
          echo "RUN_BUILD=true" >> "$GITHUB_ENV"
        fi

    - name: Download and extract the package
      if: env.RUN_BUILD == 'true'
      shell: bash
      run: |
        git rm -rf .
        git clean -fxd
        curl "${{ inputs.download_url }}" > package.zip
        bsdtar --strip-components=1 -xvf package.zip
        rm package.zip
        git reset HEAD composer.json .github
        git checkout -- composer.json .github
        git add .

    - name: Extract changelog
      if: ${{ env.RUN_BUILD == 'true' && inputs.changelog_extract != '' && inputs.changelog == '' }}
      shell: bash
      run: |
        {
          echo 'CHANGELOG<<EOF'
          ${{ inputs.changelog_extract }}
          echo -e "\n"
          echo 'EOF'
        } >> "$GITHUB_ENV"

    - name: Retrieve changelog
      if: ${{ env.RUN_BUILD == 'true' && inputs.changelog != '' }}
      shell: bash
      run: |
        {
          echo 'CHANGELOG<<EOF'
          echo "${{ inputs.changelog }}"
          echo 'EOF'
        } >> "$GITHUB_ENV"

    - name: Commit the changes and push them
      if: ${{ env.RUN_BUILD == 'true' }}
      shell: bash
      run: |
        git config --global user.name "${GITHUB_ACTOR}"
        git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
        git add .
        git commit -m "v${{ inputs.version }}" -m "${{ env.CHANGELOG }}"
        git tag --annotate ${{ inputs.version }} -m "v${{ inputs.version }}" -m "${{ env.CHANGELOG }}"
        git push
        git push origin tag ${{ inputs.version }}

    # Release workflow not triggered from other workflows
    - name: Publish release
      if: ${{ env.RUN_BUILD == 'true' }}
      uses: ghalactic/github-release-from-tag@v5

    - name: Set output status
      id: completed-job
      shell: bash
      run: |
        echo "updated=${{ env.RUN_BUILD }}" >> $GITHUB_OUTPUT
        echo "version=${{ inputs.version }}" >> $GITHUB_OUTPUT
