name: Advanced Custom Fields PRO
on:
  workflow_call:
    outputs:
      updated:
        description: "If the update didnt exist and was built"
        value: ${{ jobs.build.outputs.updated }}
      version:
        description: "The updated version"
        value: ${{ jobs.build.outputs.version }}
    secrets:
      LICENSE_KEY:
        required: true

jobs:
  build:
    name: Update plugin
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      updated: ${{ steps.update.outputs.updated }}
      version: ${{ steps.update.outputs.version }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Retrieve the package information
        run: |
          {
            echo 'LATEST_VERSION<<EOF'
            curl -s -X GET 'https://connect.advancedcustomfields.com/packages.json' | jq -r '.packages."wpengine/advanced-custom-fields-pro" | keys_unsorted [0]'
            echo 'EOF'
          } >> "$GITHUB_ENV"

      - name: Update repo
        uses: generoi/github-action-update-plugins@master
        id: update
        with:
          download_url: "https://connect.advancedcustomfields.com/v2/plugins/download?p=pro&k=${{ secrets.LICENSE_KEY }}"
          version: ${{ env.LATEST_VERSION }}
          changelog_extract: |
            awk -v ver=${{ env.LATEST_VERSION }} '/^= / { if (p) { exit }; if ($2 == ver) { p=1; next } } p && NF' readme.txt 2>&1
