name: EDD
on:
  workflow_call:
    inputs:
      slug:
        required:  true
        type: string
      source_url:
        required: true
        type: string
      endpoint_url:
        required:  true
        type: string
    secrets:
      LICENSE_KEY:
        required: true

jobs:
  build:
    name: Update plugin
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install requirement
        run: sudo apt-get install -y libarchive-tools

      # See https://easydigitaldownloads.com/docs/software-licensing-api/
      - name: Retrieve the license information
        run: |
          {
            echo 'REMOTE_RESPONSE<<EOF'
            curl -s -d "edd_action=get_version&license=${{ secrets.LICENSE_KEY }}&item_name=${{ inputs.slug }}&url=${{ inputs.source_url }}" ${{ inputs.endpoint_url }}
            echo -e "\n"
            echo 'EOF'
          } >> "$GITHUB_ENV"

      - name: Update repo
        uses: ./.github/actions/update
        with:
          download_url: ${{ fromJson(env.REMOTE_RESPONSE).download_link }}
          version: ${{ fromJson(env.REMOTE_RESPONSE).new_version }}
          changelog_extract: |
            awk -v ver=${{ fromJson(env.REMOTE_RESPONSE).new_version }} '/^= / { if (p) { exit }; if ($2 == ver) { p=1; next } } p && NF' 2>&1
