name: Freemius
on:
  workflow_call:
    inputs:
      plugin_id:
        required: true
        type: string
      site_url:
        required: true
        type: string
      changelog_extract:
        default: "'/^= / { if (p) { exit }; if ($2 == ver) { p=1; next } } p && NF'"
        type: string
    outputs:
      updated:
        description: "If the update didnt exist and was built"
        value: ${{ jobs.build.outputs.updated }}
      version:
        description: "The updated version"
        value: ${{ jobs.build.outputs.version }}
    secrets:
      FREEMIUS_USER_ID:
        required: true
      FREEMIUS_PUBLIC_KEY:
        required: true
      FREEMIUS_SECRET_KEY:
        required: true
      FREEMIUS_LICENSE_KEY:
        required: true

jobs:
  build:
    name: Update plugin
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      updated: ${{ steps.update.outputs.updated }}
      version: ${{ steps.update.outputs.version }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Checkout action scripts
        uses: actions/checkout@v5
        with:
          repository: generoi/github-action-update-plugins
          ref: master
          path: .github-action-update-plugins

      - name: Setup PHP
        uses: shivammathur/setup-php@v2

      - name: Fetch latest version and download URL
        id: remote
        env:
          FREEMIUS_USER_ID: ${{ secrets.FREEMIUS_USER_ID }}
          FREEMIUS_PUBLIC_KEY: ${{ secrets.FREEMIUS_PUBLIC_KEY }}
          FREEMIUS_SECRET_KEY: ${{ secrets.FREEMIUS_SECRET_KEY }}
          FREEMIUS_LICENSE_KEY: ${{ secrets.FREEMIUS_LICENSE_KEY }}
          FREEMIUS_PLUGIN_ID: ${{ inputs.plugin_id }}
          FREEMIUS_SITE_URL: ${{ inputs.site_url }}
        run: php .github-action-update-plugins/.github/scripts/freemius-get-package.php

      - name: Log response
        run: |
          echo "New version: ${{ steps.remote.outputs.version }}"

      - name: Update repo
        uses: generoi/github-action-update-plugins@master
        id: update
        with:
          download_url: ${{ steps.remote.outputs.download_url }}
          version: ${{ steps.remote.outputs.version }}
          changelog_extract: |-
            awk -v ver=${{ steps.remote.outputs.version }} ${{ inputs.changelog_extract }} readme.txt 2>&1

