name: Gravityforms
on:
  workflow_call:
    inputs:
      slug:
        required: false
        default: 'gravityforms'
        type: string
    outputs:
      updated:
        description: "If the update didnt exist and was built"
        value: ${{ jobs.build.outputs.updated }}
      version:
        description: "The updated version"
        value: ${{ jobs.build.outputs.version }}
    secrets:
      LICENSE_KEY:
        required: true

jobs:
  build:
    name: Update plugin
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      updated: ${{ steps.update.outputs.updated }}
      version: ${{ steps.update.outputs.version }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2

      - name: Retrieve the license information
        run: |
          {
            echo 'REMOTE_RESPONSE<<EOF'
            php -r '
              echo json_encode(
                unserialize(
                  file_get_contents(
                    "https://gravityapi.com/wp-content/plugins/gravitymanager/api.php?op=get_plugin&slug=${{ inputs.slug }}&key=${{ secrets.LICENSE_KEY }}"
                  )
                )
              );
            '
            echo -e "\n"
            echo 'EOF'
          } >> "$GITHUB_ENV"

      - name: Update repo
        uses: generoi/github-action-update-plugins@master
        id: update
        with:
          download_url: ${{ fromJson(env.REMOTE_RESPONSE).download_url_latest }}
          version: ${{ fromJson(env.REMOTE_RESPONSE).version_latest }}
          changelog_extract: |
            awk -v ver=${{ fromJson(env.REMOTE_RESPONSE).version_latest }} '/^### / { if (p) { exit }; if ($2 == ver) { p=1; next } } p && NF' change_log.txt 2>&1
