name: WooCommerce.com
on:
  workflow_call:
    inputs:
      slug:
        required: true
        type: string
    secrets:
      ACCESS_TOKEN:
        required: true
      ACCESS_TOKEN_SECRET:
        required: true

jobs:
  build:
    name: Update plugin
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2

      - name: Get package
        run: |
          curl https://raw.githubusercontent.com/generoi/github-action-update-plugins/master/.github/scripts/wccom-get-package.php > wccom-get-package.php
          {
            echo 'REMOTE_RESPONSE<<EOF'
            php wccom-get-package.php
            echo -e "\n"
            echo 'EOF'
          } >> "$GITHUB_ENV"
          rm wccom-get-package.php
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
          PRODUCT_SLUG: ${{ inputs.slug }}

      - name: Update repo
        uses: generoi/github-action-update-plugins@master
        with:
          download_url: ${{ fromJson(env.REMOTE_RESPONSE).package }}
          version: ${{ fromJson(env.REMOTE_RESPONSE).version }}
