name: WooCommerce.com
on:
  workflow_call:
    inputs:
      slug:
        required: true
        type: string
      changelog_extract:
        default: "'/[0-9\\-]+ - version/ { if (p) { exit }; if ($4 == ver) { p=1; next } } p && NF' changelog.txt"
        type: string
    outputs:
      updated:
        description: "If the update didnt exist and was built"
        value: ${{ jobs.build.outputs.updated }}
      version:
        description: "The updated version"
        value: ${{ jobs.build.outputs.version }}
    secrets:
      ACCESS_TOKEN:
        required: true
      ACCESS_TOKEN_SECRET:
        required: true

jobs:
  build:
    name: Update plugin
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      updated: ${{ steps.update.outputs.updated }}
      version: ${{ steps.update.outputs.version }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Get package
        uses: generoi/github-action-update-plugins/.github/actions/wccom-package@master
        id: wccom-package
        with:
          access_token: ${{ secrets.ACCESS_TOKEN }}
          access_token_secret: ${{ secrets.ACCESS_TOKEN_SECRET }}
          slug: ${{ inputs.slug }}

      - name: Update repo
        uses: generoi/github-action-update-plugins@master
        id: update
        with:
          download_url: ${{ fromJson(steps.wccom-package.outputs.package).package }}
          version: ${{ fromJson(steps.wccom-package.outputs.package).version }}
          changelog_extract: awk -v ver=${{ fromJson(steps.wccom-package.outputs.package).version }} ${{ inputs.changelog_extract }}
