name: WooCommerce.com
on:
  workflow_call:
    inputs:
      slug:
        required: true
        type: string
      changelog_extract:
        required: false
        type: string
    secrets:
      ACCESS_TOKEN:
        required: true
      ACCESS_TOKEN_SECRET:
        required: true

jobs:
  build:
    name: Update plugin
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Get package
        uses: generoi/github-action-update-plugins/.github/actions/wccom-package@master
        id: wccom-package
        with:
          access_token: ${{ secrets.ACCESS_TOKEN }}
          access_token_secret: ${{ secrets.ACCESS_TOKEN_SECRET }}
          slug: ${{ inputs.slug }}

      - name: Update repo
        uses: generoi/github-action-update-plugins@master
        with:
          download_url: ${{ fromJson(steps.wccom-package.outputs.package).package }}
          version: ${{ fromJson(steps.wccom-package.outputs.package).version }}
          changelog_extract: awk -v ver=${{ fromJson(steps.wccom-package.outputs.package).version }} ${{ inputs.changelog_extract }}
